/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
*/
package stack;

import javax.swing.JOptionPane;

/**
 *
 * @author AWIEZ FATHWA ZEIN
 */
public class stackGUI extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    int timeRun = 0;

    /**
     * Creates new form stackGUI
     */
    public stackGUI() {
        initComponents();
        inputcd.setText("");
        varx.setText(""); note.setVisible(false);
        vary.setText("");
        var1.setText("");
        var2.setText("");
        var3.setText("");
        var4.setText("");
        var5.setText("");
        note.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JPanel();
        note = new javax.swing.JLabel();
        cek = new javax.swing.JLabel();
        inputcd = new javax.swing.JTextField();
        top = new javax.swing.JLabel();
        ar = new javax.swing.JLabel();
        vary = new javax.swing.JTextField();
        varx = new javax.swing.JTextField();
        var6 = new javax.swing.JTextField();
        var5 = new javax.swing.JTextField();
        var4 = new javax.swing.JTextField();
        var3 = new javax.swing.JTextField();
        var1 = new javax.swing.JTextField();
        var2 = new javax.swing.JTextField();
        push = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        layer = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        note.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        note.setForeground(new java.awt.Color(0, 0, 128));
        note.setText("FULL");
        page.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, -1, -1));
        page.add(cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 420, 50));

        inputcd.setOpaque(false);
        page.add(inputcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 130, 70));
        page.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 270, 40));
        page.add(ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 270, 40));

        vary.setEditable(false);
        page.add(vary, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 70, 50));

        varx.setEditable(false);
        page.add(varx, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 70, 50));

        var6.setEditable(false);
        page.add(var6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 60, 50));

        var5.setEditable(false);
        page.add(var5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 60, 50));

        var4.setEditable(false);
        page.add(var4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 60, 50));

        var3.setEditable(false);
        page.add(var3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 60, 50));

        var1.setEditable(false);
        page.add(var1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 70, 50));

        var2.setEditable(false);
        page.add(var2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 60, 50));

        push.setOpaque(false);
        push.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pushMouseClicked(evt);
            }
        });
        push.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        page.add(push, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stack/homee.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        page.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 100, 90));

        pop.setOpaque(false);
        page.add(pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 250, 60));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        page.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 50));

        layer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stack/layer2.png"))); // NOI18N
        page.add(layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stack/bg2.jpg"))); // NOI18N
        page.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pushMouseClicked
        // TODO add your handling code here:
        String data = inputcd.getText();
        String a1 = varx.getText(); 
        String a2 = vary.getText(); 
        String b = var1.getText(); 
        String c = var2.getText(); 
        String d = var3.getText(); 
        String e = var3.getText(); 
        String f = var4.getText(); 
        if (data.equals("")){
       JOptionPane.showMessageDialog(null,"masukkan data!"); 
       
        }else {
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int a=0; a<=10; a++){
                            Thread.sleep(500);
                            if (a==1){run();}
                            if (a==2){run();}
                            if (a==3){run();}
                            if (a==4){run();}
                            if (a==4){run();}
                            if (a==5){run();}
                            if (a==6){run();}
                        }
                    }catch(Exception ex){
                                System.out.println(ex);
                                }
                }
                
                
            };th.start();
        }
        
    }//GEN-LAST:event_pushMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ar;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel cek;
    private javax.swing.JTextField inputcd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel layer;
    private javax.swing.JLabel note;
    private javax.swing.JPanel page;
    private javax.swing.JPanel pop;
    private javax.swing.JPanel push;
    private javax.swing.JLabel top;
    private javax.swing.JTextField var1;
    private javax.swing.JTextField var2;
    private javax.swing.JTextField var3;
    private javax.swing.JTextField var4;
    private javax.swing.JTextField var5;
    private javax.swing.JTextField var6;
    private javax.swing.JTextField varx;
    private javax.swing.JTextField vary;
    // End of variables declaration//GEN-END:variables
}
